# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LegUp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LegUp
  pod 'AWSCore'
  pod 'AWSDynamoDB'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  target 'LegUpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LegUpUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
